--Create USER SVC_LIME
Create user SVC_LIME PROFILE SERVICE_ACCOUNT identified by "9mU*AUDpT_Cd" default tablespace LIME_TBS;
Alter USER SVC_LIME quota unlimited on LIME_TBS;
--Create role script
CREATE ROLE LIMEUSER NOT IDENTIFIED;
PROMPT GRANTING SELECT ON DATA DICTIONARY TABLES
PROMPT GRANTING SELECT FOR OPTIONS USAGE SPECIFIC QUERIES.
PROMPT IF THE TABLE DOES NOT EXIST (ORA-00942) THEN THE CORRESPONDING OPTION IS NOT INSTALLED.
GRANT CREATE SESSION TO LIMEUSER;
GRANT CONNECT TO LIMEUSER;
GRANT SELECT ON SYS.DBA_PART_TABLES TO LIMEUSER;
GRANT SELECT ON SYS.DBA_PART_INDEXES TO LIMEUSER;
GRANT SELECT ON LOG_TRAIL TO LIMEUSER;
GRANT SELECT ON SYS.V_$VERSION TO LIMEUSER;
GRANT SELECT ON SYS.V_$OPTION TO LIMEUSER;
GRANT SELECT ON SYS.DBA_USERS TO LIMEUSER;
GRANT SELECT ON SYS.V_$SESSION TO LIMEUSER;
GRANT SELECT ON SYS.V_$LICENSE TO LIMEUSER;
GRANT SELECT ON SYS.V_$PARAMETER TO LIMEUSER;
GRANT SELECT ON SYS.DBA_FEATURE_USAGE_STATISTICS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_SEGMENTS TO LIMEUSER;
GRANT SELECT ON SYS.V_$DATABASE TO LIMEUSER;
GRANT SELECT ON SYS.V_$INSTANCE TO LIMEUSER;
GRANT SELECT ON SYS.GV_$INSTANCE TO LIMEUSER;
GRANT SELECT ON SYS.GV_$PARAMETER TO LIMEUSER;
GRANT SELECT ON SYS.DBA_TABLES TO LIMEUSER;
GRANT SELECT ON SYS.DBA_AWS TO LIMEUSER;
GRANT SELECT ON USER_SDO_GEOM_METADATA TO LIMEUSER;
GRANT SELECT ON ODM_MINING_TASK TO LIMEUSER;
GRANT SELECT ON ODM_DOCUMENT TO LIMEUSER;
GRANT SELECT ON ODM_RECORD TO LIMEUSER;
GRANT SELECT ON DMSYS.DM$OBJECT TO LIMEUSER;
GRANT SELECT ON DMSYS.DM$P_MODEL TO LIMEUSER;
GRANT SELECT ON DVSYS.DBA_DV_REALM TO LIMEUSER;
GRANT SELECT ON LBACSYS.LBAC$POLT TO LIMEUSER;
GRANT SELECT ON OLAPSYS.DBA$OLAP_CUBES TO LIMEUSER;
GRANT SELECT ON SYS.DBA_REGISTRY TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_LICENSE_DEFINITIONS TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_LICENSE_CONFIRMATION TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_TARGETS TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_ADMIN_LICENSES TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_LICENSES TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_TARGET_TYPES TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT_LICENSED_TARGETS TO LIMEUSER;
GRANT SELECT ON SYS.V_$SESSION_CONNECT_INFO TO LIMEUSER;
GRANT SELECT ON SYS.DBA_ENCRYPTED_COLUMNS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_SQL_PROFILES TO LIMEUSER;
GRANT SELECT ON SYS.DBA_CPU_USAGE_STATISTICS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_USERS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_TABLESPACES TO LIMEUSER;
GRANT SELECT ON SYS.DBA_SQL_PROFILES TO LIMEUSER;
GRANT SELECT ON SYS.MODEL$ TO LIMEUSER;
GRANT SELECT ON SYS.DBA_DATA_FILES TO LIMEUSER;
GRANT SELECT ON SYS.V_$SESSTAT TO LIMEUSER;
GRANT SELECT ON SYS.DBA_OBJECTS TO LIMEUSER;
GRANT SELECT ON SMP_REP_VERSION TO LIMEUSER;
GRANT SELECT ON SMP_VDS_REPOS_VERSION TO LIMEUSER;
GRANT SELECT ON ODM.ODM_MINING_MODEL TO LIMEUSER;
GRANT SELECT ON SYSMAN.MGMT$SOFTWARE_HOMES TO LIMEUSER;
GRANT SELECT ON ALL_SDO_GEOM_METADATA TO LIMEUSER;
GRANT SELECT ON SYS.USER_SYS_PRIVS TO LIMEUSER;
GRANT SELECT ON SYS.USER_ROLE_PRIVS TO LIMEUSER;
GRANT SELECT ON SYS.V_$ARCHIVE_DEST_STATUS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_CPU_USAGE_STATISTICS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_TAB_PARTITIONS TO LIMEUSER;
GRANT SELECT ON SYS.DBA_TAB_SUBPARTITIONS TO LIMEUSER;
--Additional Grant for LIMEUSER
GRANT SELECT ON SYS.DBA_INDEXES TO LIMEUSER;
--Assign ROLE to USER
GRANT LIMEUSER TO SVC_LIME;
--Grants to SVC_LIME user
GRANT ADMINISTER DATABASE TRIGGER TO SVC_LIME;
GRANT CREATE TRIGGER TO SVC_LIME;
GRANT CREATE TABLE TO SVC_LIME;
GRANT CREATE PROCEDURE TO SVC_LIME;
-- Additional grant to SVC_LIME.
--Required to gather "Option Requiring License Report" in the "Database Info Report"
GRANT SELECT ON sys.V_$SESSION TO SVC_LIME;
GRANT SELECT ON sys.V_$DATABASE TO SVC_LIME;
GRANT SELECT ON sys.V_$INSTANCE TO SVC_LIME;
GRANT SELECT ON sys.V_$OPTION TO SVC_LIME;
GRANT SELECT ON sys.DBA_SEGMENTS TO SVC_LIME;
GRANT SELECT ON DBA_SQL_PROFILES TO SVC_LIME;
GRANT SELECT ON OLAPSYS.DBA$OLAP_CUBES TO SVC_LIME;
GRANT SELECT ON sys.DBA_AWS TO SVC_LIME;
GRANT SELECT ON sys.GV_$PARAMETER TO SVC_LIME;
GRANT SELECT ON sys.GV_$INSTANCE TO SVC_LIME;
GRANT SELECT ON LBACSYS.LBAC$POLT TO SVC_LIME;
GRANT SELECT ON USER_SDO_GEOM_METADATA TO SVC_LIME;
GRANT SELECT ON SYS.PRODUCT_COMPONENT_VERSION TO SVC_LIME;
GRANT SELECT ON sys.DBA_FEATURE_USAGE_STATISTICS TO SVC_LIME;
GRANT SELECT ON ODM.ODM_MINING_MODEL TO SVC_LIME;
GRANT SELECT ON DMSYS.DM$MODEL TO SVC_LIME;
GRANT SELECT ON DMSYS.DM$P_MODEL TO SVC_LIME;
GRANT SELECT ON SYS.MODEL TO SVC_LIME;
GRANT SELECT ON sys.DBA_USERS TO SVC_LIME;
GRANT SELECT ON DVSYS.DBA_DV_REALM TO SVC_LIME;
GRANT SELECT ON ODM_DOCUMENT TO SVC_LIME;
GRANT SELECT ON ODM_RECORD TO SVC_LIME;
GRANT SELECT ON sys.V_$SESSION_CONNECT_INFO TO SVC_LIME;
GRANT SELECT ON sys.DBA_ENCRYPTED_COLUMNS TO SVC_LIME;
GRANT SELECT ON sys.DBA_TABLESPACES TO SVC_LIME;
GRANT SELECT ON sys.DBA_TABLES TO SVC_LIME;
GRANT SELECT ON sys.V_$SYSSTAT TO SVC_LIME;
GRANT SELECT ON sys.V_$SESSTAT TO SVC_LIME;
