# Author: KIroha
# ans-ems-oracle-lnx-cli
# Install DBClient RPM
# Note - Only Oracle versions >=19c are certified on RHEL 8
# See - https://confluence.kiroha.com/display/ED/Oracle+Database-Client+OS+Certification+-+All+Platforms

---
- name: install rhel8 rpms
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rhel8_oracle_db_client_rpms }}"
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
  tags:
    - install_rhel8_rpms

- name: install rhel7 rpms
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rhel7_oracle_db_client_rpms }}"
  register: rhel_rpm_state
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
  tags:
    - install_rhel7_rpms

- name: install rhel6 rpms
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rhel6_oracle_db_client_rpms }}"
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "6"
  tags:
    - install_rhel6_rpms

- name: install rhel5 rpms
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rhel5_oracle_db_client_rpms }}"
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "5"
  tags:
    - install_rhel5_rpms
